# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cr', models.FloatField()),
                ('xp', models.IntegerField()),
                ('race', models.CharField(blank=True, max_length=256, null=True)),
                ('alignment', models.CharField(max_length=3)),
                ('size', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=256)),
                ('subtype1', models.CharField(blank=True, max_length=256, null=True)),
                ('subtype2', models.CharField(blank=True, max_length=256, null=True)),
                ('subtype3', models.CharField(blank=True, max_length=256, null=True)),
                ('subtype4', models.CharField(blank=True, max_length=256, null=True)),
                ('subtype5', models.CharField(blank=True, max_length=256, null=True)),
                ('subtype6', models.CharField(blank=True, max_length=256, null=True)),
                ('ac', models.IntegerField()),
                ('ac_touch', models.IntegerField()),
                ('ac_ff', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('hd', models.CharField(max_length=10)),
                ('fort', models.IntegerField()),
                ('ref', models.IntegerField()),
                ('will', models.IntegerField()),
                ('melee', models.CharField(blank=True, max_length=256, null=True)),
                ('range', models.CharField(blank=True, max_length=256, null=True)),
                ('space', models.IntegerField()),
                ('reach', models.CharField(blank=True, max_length=256, null=True)),
                ('str', models.IntegerField()),
                ('dex', models.IntegerField()),
                ('int', models.IntegerField()),
                ('wis', models.IntegerField()),
                ('cha', models.IntegerField()),
                ('feats', models.CharField(blank=True, max_length=256, null=True)),
                ('skills', models.CharField(blank=True, max_length=1024, null=True)),
                ('languages', models.CharField(blank=True, max_length=256, null=True)),
                ('special_quality', models.CharField(blank=True, max_length=256, null=True)),
                ('environment', models.CharField(max_length=256)),
                ('organization', models.CharField(max_length=256)),
                ('treasure', models.CharField(blank=True, max_length=256, null=True)),
                ('speed', models.CharField(blank=True, max_length=256, null=True)),
                ('source', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
