# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='space',
            field=models.CharField(max_length=5),
        ),
    ]
