# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0002_auto_20170714_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='con',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
