# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0004_auto_20170714_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='fort',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='npc',
            name='ref',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='npc',
            name='will',
            field=models.CharField(max_length=20),
        ),
    ]
