# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='pages.Encounter')),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('initiativeBonus', models.IntegerField(default=0)),
                ('initiative', models.IntegerField(default=0)),
                ('ac', models.IntegerField()),
                ('cr', models.FloatField()),
                ('xp', models.IntegerField()),
                ('race', models.CharField(blank=True, max_length=256, null=True)),
                ('alignment', models.CharField(max_length=3)),
                ('size', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=256)),
                ('subtype1', models.CharField(blank=True, max_length=256, null=True)),
                ('subtype2', models.CharField(blank=True, max_length=256, null=True)),
                ('subtype3', models.CharField(blank=True, max_length=256, null=True)),
                ('subtype4', models.CharField(blank=True, max_length=256, null=True)),
                ('subtype5', models.CharField(blank=True, max_length=256, null=True)),
                ('subtype6', models.CharField(blank=True, max_length=256, null=True)),
                ('ac_touch', models.IntegerField()),
                ('ac_ff', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('hd', models.CharField(max_length=10)),
                ('fort', models.CharField(max_length=20)),
                ('ref', models.CharField(max_length=20)),
                ('will', models.CharField(max_length=20)),
                ('melee', models.CharField(blank=True, max_length=256, null=True)),
                ('range', models.CharField(blank=True, max_length=256, null=True)),
                ('space', models.CharField(max_length=5)),
                ('reach', models.CharField(blank=True, max_length=256, null=True)),
                ('str', models.CharField(blank=True, max_length=3, null=True)),
                ('dex', models.CharField(blank=True, max_length=3, null=True)),
                ('con', models.CharField(blank=True, max_length=3, null=True)),
                ('int', models.CharField(blank=True, max_length=3, null=True)),
                ('wis', models.CharField(blank=True, max_length=3, null=True)),
                ('cha', models.CharField(blank=True, max_length=3, null=True)),
                ('feats', models.CharField(blank=True, max_length=256, null=True)),
                ('skills', models.CharField(blank=True, max_length=1024, null=True)),
                ('languages', models.CharField(blank=True, max_length=256, null=True)),
                ('special_quality', models.CharField(blank=True, max_length=256, null=True)),
                ('environment', models.CharField(max_length=256)),
                ('organization', models.CharField(max_length=256)),
                ('treasure', models.CharField(blank=True, max_length=256, null=True)),
                ('speed', models.CharField(blank=True, max_length=256, null=True)),
                ('source', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('initiativeBonus', models.IntegerField(default=0)),
                ('initiative', models.IntegerField(default=0)),
                ('ac', models.IntegerField()),
                ('player_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('encounter', models.ManyToManyField(blank=True, to='pages.Encounter')),
                ('pcs', models.ManyToManyField(blank=True, to='pages.PC')),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='npc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.NPC'),
        ),
    ]
