# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='encounter',
        ),
        migrations.AddField(
            model_name='session',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Encounter'),
        ),
    ]
