# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='encouter',
            name='monsters',
        ),
        migrations.AddField(
            model_name='monster',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='pages.Encouter'),
        ),
        migrations.AddField(
            model_name='monster',
            name='npc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.NPC'),
        ),
    ]
