# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_pc_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pc',
            old_name='type',
            new_name='char_type',
        ),
        migrations.AddField(
            model_name='npc',
            name='char_type',
            field=models.CharField(default='npc', max_length=10),
        ),
    ]
