# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20170731_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
