# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 23:26
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_session_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='delay',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
