# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
