# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_session_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Encouter'),
        ),
        migrations.AlterField(
            model_name='session',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, to='pages.Character'),
        ),
    ]
