# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20170802_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='players',
            field=models.ManyToManyField(blank=True, to='pages.Character'),
        ),
    ]
