# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20170802_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='encounter',
        ),
        migrations.AddField(
            model_name='session',
            name='encounter',
            field=models.ManyToManyField(blank=True, to='pages.Encouter'),
        ),
    ]
