from django.db import models

# Create your models here.
class NPC(models.Model):
    name = models.CharField(max_length=256)
    cr = models.FloatField()
    xp = models.IntegerField()
    race = models.CharField(max_length=256, null=True, blank=True)
    alignment = models.CharField(max_length=3)
    size = models.CharField(max_length=20)
    type = models.CharField(max_length=256)
    subtype1 = models.CharField(max_length=256, null=True, blank=True)
    subtype2 = models.CharField(max_length=256, null=True, blank=True)
    subtype3 = models.CharField(max_length=256, null=True, blank=True)
    subtype4 = models.CharField(max_length=256, null=True, blank=True)
    subtype5 = models.CharField(max_length=256, null=True, blank=True)
    subtype6 = models.CharField(max_length=256, null=True, blank=True)
    ac = models.IntegerField()
    ac_touch = models.IntegerField()
    ac_ff = models.IntegerField()
    hp = models.IntegerField()
    hd = models.CharField(max_length=10)
    fort = models.CharField(max_length=20)
    ref = models.CharField(max_length=20)
    will = models.CharField(max_length=20)
    melee = models.CharField(max_length=256, null=True, blank=True)
    range = models.CharField(max_length=256, null=True, blank=True)
    space = models.CharField(max_length=5)
    reach = models.CharField(max_length=256, null=True, blank=True)
    str = models.IntegerField()
    dex = models.IntegerField()
    con = models.IntegerField(null=True, blank=True)
    int = models.IntegerField()
    wis = models.IntegerField()
    cha = models.IntegerField()
    feats = models.CharField(max_length=256, null=True, blank=True)
    skills = models.CharField(max_length=1024, null=True, blank=True)
    languages = models.CharField(max_length=256, null=True, blank=True)
    special_quality = models.CharField(max_length=256, null=True, blank=True)
    environment = models.CharField(max_length=256)
    organization = models.CharField(max_length=256)
    treasure = models.CharField(max_length=256, null=True, blank=True)
    speed = models.CharField(max_length=256, null=True, blank=True)
    source = models.CharField(max_length=256, null=True, blank=True)
